# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [44]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [45]:
# 1. Print the shape and column names of the dataset.
print("Shape:", df.shape)
print("Columns:")
print(df.columns)

Shape: (891, 12)
Columns:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [46]:
# 2. Display basic information and summary statistics about the dataset.
print("\nBasic information:")
df.info()

print("\nSummary statistics:")
display(df.describe())

Basic information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Summary statistics:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [47]:
# 3. Show the first 10 rows.
print(df.head(10))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [48]:
# 1. Select the names column
df["Name"].head(10)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                        Palsson, Master Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [49]:
# 2. Select multiple columns
df[["Name", "Sex", "Age"]].head(10)

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                              Heikkinen, Miss Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                      Palsson, Master Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [50]:
# 3. Select a single row
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [51]:
# 4. Select a rectangular section
df.iloc[0:5, 0:4]

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [52]:
# 1. Rows where age is above 60
df[df["Age"] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [53]:
# 2. Rows where fare is above 100 and passenger was in 1st class
df[(df["Fare"] > 100) & (df["Pclass"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [54]:
# 3. Rows where age is missing
df[df["Age"].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [55]:
# 1. Reverse the row order
df_reversed = df[::-1].reset_index(drop=True)

df_reversed.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
1,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
2,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
3,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
4,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
5,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
6,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
7,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
8,883,0,3,"Dahlberg, Miss Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
9,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S

In [56]:
# 2. Remove one column, for example Ticket
df_no_cabin = df.drop(columns=["Ticket"])

df_no_cabin.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,30.0708,NaN,C

In [57]:
# 3. Remove rows with missing values in Age
df_age_clean = df.dropna(subset=["Age"])

# Check original shape and new shape
print("Original shape:", df.shape)
print("After removing missing Age rows:", df_age_clean.shape)

Original shape: (891, 12)
After removing missing Age rows: (714, 12)

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [58]:
# 1. Convert fare from USD to Euros
df["Fare_Euros"] = df["Fare"] * 0.92

# Check the new column
df[["Fare", "Fare_Euros"]].head(10)

      Fare  Fare_Euros
0   7.2500    6.670000
1  71.2833   65.580636
2   7.9250    7.291000
3  53.1000   48.852000
4   8.0500    7.406000
5   8.4583    7.781636
6  51.8625   47.713500
7  21.0750   19.389000
8  11.1333   10.242636
9  30.0708   27.665136

In [59]:
# 2. Subtract the average age from every age value
average_age = df["Age"].mean()

df["Age_minus_average"] = df["Age"] - average_age

print("Average age:", average_age)

df[["Name", "Age", "Age_minus_average"]].head(10)

Average age: 29.69911764705882

                                                Name   Age  Age_minus_average
0                            Braund, Mr. Owen Harris  22.0          -7.699118
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0           8.300882
2                              Heikkinen, Miss Laina  26.0          -3.699118
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0           5.300882
4                           Allen, Mr. William Henry  35.0           5.300882
5                                   Moran, Mr. James   NaN                NaN
6                            McCarthy, Mr. Timothy J  54.0          24.300882
7                      Palsson, Master Gosta Leonard   2.0         -27.699118
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0          -2.699118
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0         -15.699118

In [60]:
# 3. Subtract a custom array from two selected columns
df_age_fare_adjusted = df[["Age", "Fare"]] - [10, 50]

df_age_fare_adjusted.head(10)

    Age     Fare
0  12.0 -42.7500
1  28.0  21.2833
2  16.0 -42.0750
3  25.0   3.1000
4  25.0 -41.9500
5   NaN -41.5417
6  44.0   1.8625
7  -8.0 -28.9250
8  17.0 -38.8667
9   4.0 -19.9292

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [61]:
# 1. Create a new column with the number of characters in each name
df["Name_Length"] = df["Name"].str.len()

df[["Name", "Name_Length"]].head(10)

                                                Name  Name_Length
0                            Braund, Mr. Owen Harris           23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...           51
2                              Heikkinen, Miss Laina           21
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)           44
4                           Allen, Mr. William Henry           24
5                                   Moran, Mr. James           16
6                            McCarthy, Mr. Timothy J           23
7                      Palsson, Master Gosta Leonard           29
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)           49
9                Nasser, Mrs. Nicholas (Adele Achem)           35

In [62]:
# 2. Calculate the difference between fare and age for each row
df["Fare_minus_Age"] = df["Fare"] - df["Age"]

df[["Name", "Fare", "Age", "Fare_minus_Age"]].head(10)

,Name,Fare,Age,Fare_minus_Age
0,"Braund, Mr. Owen Harris",7.2500,22.0,-14.7500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,38.0,33.2833
2,"Heikkinen, Miss Laina",7.9250,26.0,-18.0750
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,35.0,18.1000
4,"Allen, Mr. William Henry",8.0500,35.0,-26.9500
5,"Moran, Mr. James",8.4583,NaN,NaN
6,"McCarthy, Mr. Timothy J",51.8625,54.0,-2.1375
7,"Palsson, Master Gosta Leonard",21.0750,2.0,19.0750
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",11.1333,27.0,-15.8667
9,"Nasser, Mrs. Nicholas (Adele Achem)",30.0708,14.0,16.0708

In [63]:
# 3. Round all numerical values to one decimal place
df_rounded = df.round(1)

df_rounded.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros,Age_minus_average,Name_Length,Fare_minus_Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2,NaN,S,6.7,-7.7,23,-14.8
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.3,C85,C,65.6,8.3,51,33.3
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,7.3,-3.7,21,-18.1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,48.9,5.3,44,18.1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0,NaN,S,7.4,5.3,24,-27.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.5,NaN,Q,7.8,NaN,16,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.9,E46,S,47.7,24.3,23,-2.1
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.1,NaN,S,19.4,-27.7,29,19.1
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1,NaN,S,10.2,-2.7,49,-15.9
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.1,NaN,C,27.7,-15.7,35,16.1

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [64]:
# 1. Convert gender/Sex values to numeric codes
df["Sex_Code"] = df["Sex"].map({
    "male": 0,
    "female": 1
})

df[["Name", "Sex", "Sex_Code"]].head(10)

                                                Name     Sex  Sex_Code
0                            Braund, Mr. Owen Harris    male         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female         1
2                              Heikkinen, Miss Laina  female         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female         1
4                           Allen, Mr. William Henry    male         0
5                                   Moran, Mr. James    male         0
6                            McCarthy, Mr. Timothy J    male         0
7                      Palsson, Master Gosta Leonard    male         0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female         1
9                Nasser, Mrs. Nicholas (Adele Achem)  female         1

In [65]:
# 2. Create age groups
def categorize_age(age):
    if pd.isna(age):
        return "unknown"
    elif age < 18:
        return "child"
    elif age < 60:
        return "adult"
    else:
        return "senior"

df["Age_Group"] = df["Age"].apply(categorize_age)

df[["Name", "Age", "Age_Group"]].head(20)

                                                 Name   Age Age_Group
0                             Braund, Mr. Owen Harris  22.0     adult
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0     adult
2                               Heikkinen, Miss Laina  26.0     adult
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0     adult
4                            Allen, Mr. William Henry  35.0     adult
5                                    Moran, Mr. James   NaN   unknown
6                             McCarthy, Mr. Timothy J  54.0     adult
7                       Palsson, Master Gosta Leonard   2.0     child
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0     adult
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0     child
10                     Sandstrom, Miss Marguerite Rut   4.0     child
11                            Bonnell, Miss Elizabeth  58.0     adult
12                     Saundercock, Mr. William Henry  20.0     adult
13                        Andersson, Mr. Anders Johan  39.0     adult
14                Vestrom, Miss Hulda Amanda Adolfina  14.0     child
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0     adult
16                                Rice, Master Eugene   2.0     child
17                       Williams, Mr. Charles Eugene   NaN   unknown
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0     adult
19                            Masselmani, Mrs. Fatima   NaN   unknown

### Part 8: Solving the task without Panda ###
 Choose one task from each of Parts 2, 3, or 5 (3 tasks in total). Try to solve that chosen task without using Pandas, only with pure Python code.

In [66]:
import csv

# Load the CSV file without pandas
with open("titanic.csv", "r", encoding="utf-8") as file:
    reader = csv.DictReader(file)
    data = list(reader)

print(data)

[{'PassengerId': '1', 'Survived': '0', 'Pclass': '3', 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': '22', 'SibSp': '1', 'Parch': '0', 'Ticket': 'A/5 21171', 'Fare': '7.25', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '2', 'Survived': '1', 'Pclass': '1', 'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Sex': 'female', 'Age': '38', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17599', 'Fare': '71.2833', 'Cabin': 'C85', 'Embarked': 'C'}, {'PassengerId': '3', 'Survived': '1', 'Pclass': '3', 'Name': 'Heikkinen, Miss Laina', 'Sex': 'female', 'Age': '26', 'SibSp': '0', 'Parch': '0', 'Ticket': 'STON/O2. 3101282', 'Fare': '7.925', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '4', 'Survived': '1', 'Pclass': '1', 'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Sex': 'female', 'Age': '35', 'SibSp': '1', 'Parch': '0', 'Ticket': '113803', 'Fare': '53.1', 'Cabin': 'C123', 'Embarked': 'S'}, {'PassengerId': '5', 'Survived': '0', 'Pclass': '3', 'Name': 'Allen, Mr. William Henry', 'Sex': 'male', 'Age': '35', 'SibSp': '0', 'Parch': '0', 'Ticket': '373450', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '6', 'Survived': '0', 'Pclass': '3', 'Name': 'Moran, Mr. James', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '330877', 'Fare': '8.4583', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '7', 'Survived': '0', 'Pclass': '1', 'Name': 'McCarthy, Mr. Timothy J', 'Sex': 'male', 'Age': '54', 'SibSp': '0', 'Parch': '0', 'Ticket': '17463', 'Fare': '51.8625', 'Cabin': 'E46', 'Embarked': 'S'}, {'PassengerId': '8', 'Survived': '0', 'Pclass': '3', 'Name': 'Palsson, Master Gosta Leonard', 'Sex': 'male', 'Age': '2', 'SibSp': '3', 'Parch': '1', 'Ticket': '349909', 'Fare': '21.075', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '9', 'Survived': '1', 'Pclass': '3', 'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'Sex': 'female', 'Age': '27', 'SibSp': '0', 'Parch': '2', 'Ticket': '347742', 'Fare': '11.1333', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '10', 'Survived': '1', 'Pclass': '2', 'Name': 'Nasser, Mrs. Nicholas (Adele Achem)', 'Sex': 'female', 'Age': '14', 'SibSp': '1', 'Parch': '0', 'Ticket': '237736', 'Fare': '30.0708', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '11', 'Survived': '1', 'Pclass': '3', 'Name': 'Sandstrom, Miss Marguerite Rut', 'Sex': 'female', 'Age': '4', 'SibSp': '1', 'Parch': '1', 'Ticket': 'PP 9549', 'Fare': '16.7', 'Cabin': 'G6', 'Embarked': 'S'}, {'PassengerId': '12', 'Survived': '1', 'Pclass': '1', 'Name': 'Bonnell, Miss Elizabeth', 'Sex': 'female', 'Age': '58', 'SibSp': '0', 'Parch': '0', 'Ticket': '113783', 'Fare': '26.55', 'Cabin': 'C103', 'Embarked': 'S'}, {'PassengerId': '13', 'Survived': '0', 'Pclass': '3', 'Name': 'Saundercock, Mr. William Henry', 'Sex': 'male', 'Age': '20', 'SibSp': '0', 'Parch': '0', 'Ticket': 'A/5. 2151', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '14', 'Survived': '0', 'Pclass': '3', 'Name': 'Andersson, Mr. Anders Johan', 'Sex': 'male', 'Age': '39', 'SibSp': '1', 'Parch': '5', 'Ticket': '347082', 'Fare': '31.275', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '15', 'Survived': '0', 'Pclass': '3', 'Name': 'Vestrom, Miss Hulda Amanda Adolfina', 'Sex': 'female', 'Age': '14', 'SibSp': '0', 'Parch': '0', 'Ticket': '350406', 'Fare': '7.8542', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '16', 'Survived': '1', 'Pclass': '2', 'Name': 'Hewlett, Mrs. (Mary D Kingcome) ', 'Sex': 'female', 'Age': '55', 'SibSp': '0', 'Parch': '0', 'Ticket': '248706', 'Fare': '16', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '17', 'Survived': '0', 'Pclass': '3', 'Name': 'Rice, Master Eugene', 'Sex': 'male', 'Age': '2', 'SibSp': '4', 'Parch': '1', 'Ticket': '382652', 'Fare': '29.125', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '18', 'Survived': '1', 'Pclass': '2', 'Name': 'Williams, Mr. Charles Eugene', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '244373', 'Fare': '13', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '19', 'Survived': '0', 'Pclass': '3', 'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'Sex': 'female', 'Age': '31', 'SibSp': '1', 'Parch': '0', 'Ticket': '345763', 'Fare': '18', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '20', 'Survived': '1', 'Pclass': '3', 'Name': 'Masselmani, Mrs. Fatima', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '2649', 'Fare': '7.225', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '21', 'Survived': '0', 'Pclass': '2', 'Name': 'Fynney, Mr. Joseph J', 'Sex': 'male', 'Age': '35', 'SibSp': '0', 'Parch': '0', 'Ticket': '239865', 'Fare': '26', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '22', 'Survived': '1', 'Pclass': '2', 'Name': 'Beesley, Mr. Lawrence', 'Sex': 'male', 'Age': '34', 'SibSp': '0', 'Parch': '0', 'Ticket': '248698', 'Fare': '13', 'Cabin': 'D56', 'Embarked': 'S'}, {'PassengerId': '23', 'Survived': '1', 'Pclass': '3', 'Name': 'McGowan, Miss Anna "Annie"', 'Sex': 'female', 'Age': '15', 'SibSp': '0', 'Parch': '0', 'Ticket': '330923', 'Fare': '8.0292', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '24', 'Survived': '1', 'Pclass': '1', 'Name': 'Sloper, Mr. William Thompson', 'Sex': 'male', 'Age': '28', 'SibSp': '0', 'Parch': '0', 'Ticket': '113788', 'Fare': '35.5', 'Cabin': 'A6', 'Embarked': 'S'}, {'PassengerId': '25', 'Survived': '0', 'Pclass': '3', 'Name': 'Palsson, Miss Torborg Danira', 'Sex': 'female', 'Age': '8', 'SibSp': '3', 'Parch': '1', 'Ticket': '349909', 'Fare': '21.075', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '26', 'Survived': '1', 'Pclass': '3', 'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'Sex': 'female', 'Age': '38', 'SibSp': '1', 'Parch': '5', 'Ticket': '347077', 'Fare': '31.3875', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '27', 'Survived': '0', 'Pclass': '3', 'Name': 'Emir, Mr. Farred Chehab', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '2631', 'Fare': '7.225', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '28', 'Survived': '0', 'Pclass': '1', 'Name': 'Fortune, Mr. Charles Alexander', 'Sex': 'male', 'Age': '19', 'SibSp': '3', 'Parch': '2', 'Ticket': '19950', 'Fare': '263', 'Cabin': 'C23 C25 C27', 'Embarked': 'S'}, {'PassengerId': '29', 'Survived': '1', 'Pclass': '3', 'Name': 'O\'Dwyer, Miss Ellen "Nellie"', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '330959', 'Fare': '7.8792', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '30', 'Survived': '0', 'Pclass': '3', 'Name': 'Todoroff, Mr. Lalio', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '349216', 'Fare': '7.8958', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '31', 'Survived': '0', 'Pclass': '1', 'Name': 'Uruchurtu, Don. Manuel E', 'Sex': 'male', 'Age': '40', 'SibSp': '0', 'Parch': '0', 'Ticket': 'PC 17601', 'Fare': '27.7208', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '32', 'Survived': '1', 'Pclass': '1', 'Name': 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'Sex': 'female', 'Age': '', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17569', 'Fare': '146.5208', 'Cabin': 'B78', 'Embarked': 'C'}, {'PassengerId': '33', 'Survived': '1', 'Pclass': '3', 'Name': 'Glynn, Miss Mary Agatha', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '335677', 'Fare': '7.75', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '34', 'Survived': '0', 'Pclass': '2', 'Name': 'Wheadon, Mr. Edward H', 'Sex': 'male', 'Age': '66', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 24579', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '35', 'Survived': '0', 'Pclass': '1', 'Name': 'Meyer, Mr. Edgar Joseph', 'Sex': 'male', 'Age': '28', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17604', 'Fare': '82.1708', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '36', 'Survived': '0', 'Pclass': '1', 'Name': 'Holverson, Mr. Alexander Oskar', 'Sex': 'male', 'Age': '42', 'SibSp': '1', 'Parch': '0', 'Ticket': '113789', 'Fare': '52', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '37', 'Survived': '1', 'Pclass': '3', 'Name': 'Mamee, Mr. Hanna', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '2677', 'Fare': '7.2292', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '38', 'Survived': '0', 'Pclass': '3', 'Name': 'Cann, Mr. Ernest Charles', 'Sex': 'male', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'A./5. 2152', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '39', 'Survived': '0', 'Pclass': '3', 'Name': 'Vander Planke, Miss Augusta Maria', 'Sex': 'female', 'Age': '18', 'SibSp': '2', 'Parch': '0', 'Ticket': '345764', 'Fare': '18', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '40', 'Survived': '1', 'Pclass': '3', 'Name': 'Nicola-Yarred, Miss Jamila', 'Sex': 'female', 'Age': '14', 'SibSp': '1', 'Parch': '0', 'Ticket': '2651', 'Fare': '11.2417', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '41', 'Survived': '0', 'Pclass': '3', 'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'Sex': 'female', 'Age': '40', 'SibSp': '1', 'Parch': '0', 'Ticket': '7546', 'Fare': '9.475', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '42', 'Survived': '0', 'Pclass': '2', 'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'Sex': 'female', 'Age': '27', 'SibSp': '1', 'Parch': '0', 'Ticket': '11668', 'Fare': '21', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '43', 'Survived': '0', 'Pclass': '3', 'Name': 'Kraeff, Mr. Theodor', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '349253', 'Fare': '7.8958', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '44', 'Survived': '1', 'Pclass': '2', 'Name': 'Laroche, Miss Simonne Marie Anne Andree', 'Sex': 'female', 'Age': '3', 'SibSp': '1', 'Parch': '2', 'Ticket': 'SC/Paris 2123', 'Fare': '41.5792', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '45', 'Survived': '1', 'Pclass': '3', 'Name': 'Devaney, Miss Margaret Delia', 'Sex': 'female', 'Age': '19', 'SibSp': '0', 'Parch': '0', 'Ticket': '330958', 'Fare': '7.8792', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '46', 'Survived': '0', 'Pclass': '3', 'Name': 'Rogers, Mr. William John', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': 'S.C./A.4. 23567', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '47', 'Survived': '0', 'Pclass': '3', 'Name': 'Lennon, Mr. Denis', 'Sex': 'male', 'Age': '', 'SibSp': '1', 'Parch': '0', 'Ticket': '370371', 'Fare': '15.5', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '48', 'Survived': '1', 'Pclass': '3', 'Name': "O'Driscoll, Miss Bridget", 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '14311', 'Fare': '7.75', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '49', 'Survived': '0', 'Pclass': '3', 'Name': 'Samaan, Mr. Youssef', 'Sex': 'male', 'Age': '', 'SibSp': '2', 'Parch': '0', 'Ticket': '2662', 'Fare': '21.6792', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '50', 'Survived': '0', 'Pclass': '3', 'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'Sex': 'female', 'Age': '18', 'SibSp': '1', 'Parch': '0', 'Ticket': '349237', 'Fare': '17.8', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '51', 'Survived': '0', 'Pclass': '3', 'Name': 'Panula, Master Juha Niilo', 'Sex': 'male', 'Age': '7', 'SibSp': '4', 'Parch': '1', 'Ticket': '3101295', 'Fare': '39.6875', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '52', 'Survived': '0', 'Pclass': '3', 'Name': 'Nosworthy, Mr. Richard Cater', 'Sex': 'male', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'A/4. 39886', 'Fare': '7.8', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '53', 'Survived': '1', 'Pclass': '1', 'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Sex': 'female', 'Age': '49', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17572', 'Fare': '76.7292', 'Cabin': 'D33', 'Embarked': 'C'}, {'PassengerId': '54', 'Survived': '1', 'Pclass': '2', 'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'Sex': 'female', 'Age': '29', 'SibSp': '1', 'Parch': '0', 'Ticket': '2926', 'Fare': '26', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '55', 'Survived': '0', 'Pclass': '1', 'Name': 'Ostby, Mr. Engelhart Cornelius', 'Sex': 'male', 'Age': '65', 'SibSp': '0', 'Parch': '1', 'Ticket': '113509', 'Fare': '61.9792', 'Cabin': 'B30', 'Embarked': 'C'}, {'PassengerId': '56', 'Survived': '1', 'Pclass': '1', 'Name': 'Woolner, Mr. Hugh', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '19947', 'Fare': '35.5', 'Cabin': 'C52', 'Embarked': 'S'}, {'PassengerId': '57', 'Survived': '1', 'Pclass': '2', 'Name': 'Rugg, Miss Emily', 'Sex': 'female', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 31026', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '58', 'Survived': '0', 'Pclass': '3', 'Name': 'Novel, Mr. Mansouer', 'Sex': 'male', 'Age': '28.5', 'SibSp': '0', 'Parch': '0', 'Ticket': '2697', 'Fare': '7.2292', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '59', 'Survived': '1', 'Pclass': '2', 'Name': 'West, Miss Constance Mirium', 'Sex': 'female', 'Age': '5', 'SibSp': '1', 'Parch': '2', 'Ticket': 'C.A. 34651', 'Fare': '27.75', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '60', 'Survived': '0', 'Pclass': '3', 'Name': 'Goodwin, Master William Frederick', 'Sex': 'male', 'Age': '11', 'SibSp': '5', 'Parch': '2', 'Ticket': 'CA 2144', 'Fare': '46.9', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '61', 'Survived': '0', 'Pclass': '3', 'Name': 'Sirayanian, Mr. Orsen', 'Sex': 'male', 'Age': '22', 'SibSp': '0', 'Parch': '0', 'Ticket': '2669', 'Fare': '7.2292', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '62', 'Survived': '1', 'Pclass': '1', 'Name': 'Icard, Miss Amelie', 'Sex': 'female', 'Age': '38', 'SibSp': '0', 'Parch': '0', 'Ticket': '113572', 'Fare': '80', 'Cabin': 'B28', 'Embarked': ''}, {'PassengerId': '63', 'Survived': '0', 'Pclass': '1', 'Name': 'Harris, Mr. Henry Birkhardt', 'Sex': 'male', 'Age': '45', 'SibSp': '1', 'Parch': '0', 'Ticket': '36973', 'Fare': '83.475', 'Cabin': 'C83', 'Embarked': 'S'}, {'PassengerId': '64', 'Survived': '0', 'Pclass': '3', 'Name': 'Skoog, Master Harald', 'Sex': 'male', 'Age': '4', 'SibSp': '3', 'Parch': '2', 'Ticket': '347088', 'Fare': '27.9', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '65', 'Survived': '0', 'Pclass': '1', 'Name': 'Stewart, Mr. Albert A', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': 'PC 17605', 'Fare': '27.7208', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '66', 'Survived': '1', 'Pclass': '3', 'Name': 'Moubarek, Master Gerios', 'Sex': 'male', 'Age': '', 'SibSp': '1', 'Parch': '1', 'Ticket': '2661', 'Fare': '15.2458', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '67', 'Survived': '1', 'Pclass': '2', 'Name': 'Nye, Mrs. (Elizabeth Ramell)', 'Sex': 'female', 'Age': '29', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 29395', 'Fare': '10.5', 'Cabin': 'F33', 'Embarked': 'S'}, {'PassengerId': '68', 'Survived': '0', 'Pclass': '3', 'Name': 'Crease, Mr. Ernest James', 'Sex': 'male', 'Age': '19', 'SibSp': '0', 'Parch': '0', 'Ticket': 'S.P. 3464', 'Fare': '8.1583', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '69', 'Survived': '1', 'Pclass': '3', 'Name': 'Andersson, Miss Erna Alexandra', 'Sex': 'female', 'Age': '17', 'SibSp': '4', 'Parch': '2', 'Ticket': '3101281', 'Fare': '7.925', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '70', 'Survived': '0', 'Pclass': '3', 'Name': 'Kink, Mr. Vincenz', 'Sex': 'male', 'Age': '26', 'SibSp': '2', 'Parch': '0', 'Ticket': '315151', 'Fare': '8.6625', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '71', 'Survived': '0', 'Pclass': '2', 'Name': 'Jenkin, Mr. Stephen Curnow', 'Sex': 'male', 'Age': '32', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 33111', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '72', 'Survived': '0', 'Pclass': '3', 'Name': 'Goodwin, Miss Lillian Amy', 'Sex': 'female', 'Age': '16', 'SibSp': '5', 'Parch': '2', 'Ticket': 'CA 2144', 'Fare': '46.9', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '73', 'Survived': '0', 'Pclass': '2', 'Name': 'Hood, Mr. Ambrose Jr', 'Sex': 'male', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'S.O.C. 14879', 'Fare': '73.5', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '74', 'Survived': '0', 'Pclass': '3', 'Name': 'Chronopoulos, Mr. Apostolos', 'Sex': 'male', 'Age': '26', 'SibSp': '1', 'Parch': '0', 'Ticket': '2680', 'Fare': '14.4542', 'Cabin': '', 'Embarked': 'C'}, {'PassengerId': '75', 'Survived': '1', 'Pclass': '3', 'Name': 'Bing, Mr. Lee', 'Sex': 'male', 'Age': '32', 'SibSp': '0', 'Parch': '0', 'Ticket': '1601', 'Fare': '56.4958', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '76', 'Survived': '0', 'Pclass': '3', 'Name': 'Moen, Mr. Sigurd Hansen', 'Sex': 'male', 'Age': '25', 'SibSp': '0', 'Parch': '0', 'Ticket': '348123', 'Fare': '7.65', 'Cabin': 'F G73', 'Embarked': 'S'}, {'PassengerId': '77', 'Survived': '0', 'Pclass': '3', 'Name': 'Staneff, Mr. Ivan', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '349208', 'Fare': '7.8958', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '78', 'Survived': '0', 'Pclass': '3', 'Name': 'Moutal, Mr. Rahamin Haim', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '374746', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '79', 'Survived': '1', 'Pclass': '2', 'Name': 'Caldwell, Master Alden Gates', 'Sex': 'male', 'Age': '0.83', 'SibSp': '0', 'Parch': '2', 'Ticket': '248738', 'Fare': '29', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '80', 'Survived': '1', 'Pclass': '3', 'Name': 'Dowdell, Miss Elizabeth', 'Sex': 'female', 'Age': '30', 'SibSp': '0', 'Parch': '0', 'Ticket': '364516', 'Fare': '12.475', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '81', 'Survived': '0', 'Pclass': '3', 'Name': 'Waelens, Mr. Achille', 'Sex': 'male', 'Age': '22', 'SibSp': '0', 'Parch': '0', 'Ticket': '345767', 'Fare': '9', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '82', 'Survived': '1', 'Pclass': '3', 'Name': 'Sheerlinck, Mr. Jan Baptist', 'Sex': 'male', 'Age': '29', 'SibSp': '0', 'Parch': '0', 'Ticket': '345779', 'Fare': '9.5', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '83', 'Survived': '1', 'Pclass': '3', 'Name': 'McDermott, Miss Brigdet Delia', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '330932', 'Fare': '7.7875', 'Cabin': '', 'Embarked': 'Q'}, {'PassengerId': '84', 'Survived': '0', 'Pclass': '1', 'Name': 'Carrau, Mr. Francisco M', 'Sex': 'male', 'Age': '28', 'SibSp': '0', 'Parch': '0', 'Ticket': '113059', 'Fare': '47.1', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '85', 'Survived': '1', 'Pclass': '2', 'Name': 'Ilett, Miss Bertha', 'Sex': 'female', 'Age': '17', 'SibSp': '0', 'Parch': '0', 'Ticket': 'SO/C 14885', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '86', 'Survived': '1', 'Pclass': '3', 'Name': 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'Sex': 'female', 'Age': '33', 'SibSp': '3', 'Parch': '0', 'Ticket': '3101278', 'Fare': '15.85', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '87', 'Survived': '0', 'Pclass': '3', 'Name': 'Ford, Mr. William Neal', 'Sex': 'male', 'Age': '16', 'SibSp': '1', 'Parch': '3', 'Ticket': 'W./C. 6608', 'Fare': '34.375', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '88', 'Survived': '0', 'Pclass': '3', 'Name': 'Slocovski, Mr. Selman Francis', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': 'SOTON/OQ 392086', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '89', 'Survived': '1', 'Pclass': '1', 'Name': 'Fortune, Miss Mabel Helen', 'Sex': 'female', 'Age': '23', 'SibSp': '3', 'Parch': '2', 'Ticket': '19950', 'Fare': '263', 'Cabin': 'C23 C25 C27', 'Embarked': 'S'}, {'PassengerId': '90', 'Survived': '0', 'Pclass': '3', 'Name': 'Celotti, Mr. Francesco', 'Sex': 'male', 'Age': '24', 'SibSp': '0', 'Parch': '0', 'Ticket': '343275', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '91', 'Survived': '0', 'Pclass': '3', 'Name': 'Christmann, Mr. Emil', 'Sex': 'male', 'Age': '29', 'SibSp': '0', 'Parch': '0', 'Ticket': '343276', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S'}, {'PassengerId': '92', 'Survived': '0', 'Pclass': '3

In [67]:
# Part 2 task: Select the names column
names = [row["Name"] for row in data]

print("First 10 names:")
print(names[:10])

First 10 names:
['Braund, Mr. Owen Harris', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss Laina', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Allen, Mr. William Henry', 'Moran, Mr. James', 'McCarthy, Mr. Timothy J', 'Palsson, Master Gosta Leonard', 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'Nasser, Mrs. Nicholas (Adele Achem)']

In [68]:
# Part 3 task: Show rows where age is above 60
age_above_60 = []

for row in data:
    if row["Age"] != "":
        age = float(row["Age"])

        if age > 60:
            age_above_60.append(row)

print("\nPassengers above age 60:")
for row in age_above_60:
    print(row["Name"], row["Age"])

Passengers above age 60:
Wheadon, Mr. Edward H 66
Ostby, Mr. Engelhart Cornelius 65
Goldschmidt, Mr. George B 71
Connors, Mr. Patrick 70.5
Van der hoef, Mr. Wyckoff 61
Stead, Mr. William Thomas 62
Andrews, Miss Kornelia Theodosia 63
Duane, Mr. Frank 65
Nysveen, Mr. Johan Hansen 61
Fortune, Mr. Mark 64
Millet, Mr. Francis Davis 65
Turkula, Mrs. (Hedwig) 63
Artagaveytia, Mr. Ramon 71
Nicholson, Mr. Arthur Ernest 64
Wright, Mr. George 62
Harris, Mr. George 62
Sutton, Mr. Frederick 61
Barkworth, Mr. Algernon Henry Wilson 80
Mitchell, Mr. Henry Michael 70
Crosby, Capt. Edward Gifford 70
Stone, Mrs. George Nelson (Martha Evelyn) 62
Svensson, Mr. Johan 74

In [69]:
# Part 5 task: Create a new fare-in-Euros value
for row in data:
    fare_usd = float(row["Fare"])
    fare_euros = fare_usd * 0.92

    row["Fare_Euros"] = fare_euros

print("\nFirst 10 fares in USD and Euros:")
for row in data[:10]:
    print(row["Name"], row["Fare"], row["Fare_Euros"])

First 10 fares in USD and Euros:
Braund, Mr. Owen Harris 7.25 6.67
Cumings, Mrs. John Bradley (Florence Briggs Thayer) 71.2833 65.580636
Heikkinen, Miss Laina 7.925 7.291
Futrelle, Mrs. Jacques Heath (Lily May Peel) 53.1 48.852000000000004
Allen, Mr. William Henry 8.05 7.406000000000001
Moran, Mr. James 8.4583 7.781636
McCarthy, Mr. Timothy J 51.8625 47.713499999999996
Palsson, Master Gosta Leonard 21.075 19.389
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) 11.1333 10.242636000000001
Nasser, Mrs. Nicholas (Adele Achem) 30.0708 27.665136

### Comparison in the execution time ###

In [70]:
import pandas as pd
import csv
import time

# Pandas version
start_time = time.time()

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

names_pandas = df["Name"]

age_above_60_pandas = df[df["Age"] > 60]

df["Fare_Euros"] = df["Fare"] * 0.92

end_time = time.time()

pandas_time = end_time - start_time



# Pure Python version
start_time = time.time()

with open("titanic.csv", "r", encoding="utf-8") as file:
    reader = csv.DictReader(file)
    data = list(reader)

names_python = [row["Name"] for row in data]

age_above_60_python = []

for row in data:
    if row["Age"] != "":
        age = float(row["Age"])

        if age > 60:
            age_above_60_python.append(row)

for row in data:
    fare_usd = float(row["Fare"])
    fare_euros = fare_usd * 0.92

    row["Fare_Euros"] = fare_euros

end_time = time.time()

python_time = end_time - start_time


# Results
print("Pandas execution time:", pandas_time)
print("Pure Python execution time:", python_time)

if pandas_time < python_time:
    print("Pandas was faster.")
else:
    print("Pure Python was faster.")

Pandas execution time: 0.062098026275634766
Pure Python execution time: 0.004695415496826172
Pure Python was faster.

For this small dataset, pure Python was faster.
However, pandas is easier to write, easier to read and read and better for larger data analysis tasks.